### ISSUE TITLE
Droplink Bypass not working 

### ISSUE THREAD

**Issue by im-vivektomar** [TheCaduceus/Link-Bypasser#5]
Please take a look droplink Bypass not working

**Comment by TheCaduceus** [comment]
@im-vivektomar Provide the droplink that producing the error.

**Comment by TheCaduceus** [comment]
![image](https://user-images.githubusercontent.com/87380104/187083184-b7c55ee6-3a5e-46ce-a198-76f11d86151a.png)
It is working as expected!
